sudo: required
services:
  - docker

script:
  - docker build -t "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker tag "$IMAGE_NAME" "tolujimoh/${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "tolujimoh/${IMAGE_NAME}:latest"
  on:
    branch: master